Implement verification library
AdguardTeam/VerificationLibrary pull request #2
Opened 2017-07-03 10:53 UTC by sfionov

Implemented verification library with CRLSet, HPKP, OCSP and SHA1 deprecation checks.

Fixes #1, AdguardTeam/CoreLibs#10

2017-07-03 11:06 UTC, hmage approved these changes

2017-07-03 11:09 UTC, sxgunchenko approved these changes

2017-07-03 12:20 UTC, ameshkov requested changes

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> + * CRLSets CRX download URL: http://clients2.google.com/service/update2/crx?response=redirect&x=id%3Dhfnkpimlhhgieaddgfemjhofmfblmnib%26v=%26uc
Can we override that URL?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> +AGVerifyResult AGCertificateVerifier::verifyRevocations(STACK_OF(X509) *certChain) {
It makes sense to emphasize that we check CRLSets: `verifyCrlSetsStatus`

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> +AGVerifyResult AGCertificateVerifier::verifyRevocations(STACK_OF(X509) *certChain) {
There should be a link to CRLSets description

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> + * Update HPKP pinning information
There should be a link to HPKP definition.
It's not clear when this method should be called by the client.

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> + * Verify that certificate chain has no untrusted authorities
It's not clear what exactly does this method do. What kind of untrusted authorities? Why can't they be in the chain?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> + * Verify that certificate chain has no untrusted authorities
Ok, got it from the code. Method description is still unclear, though.

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> + * Verifies only certificates issued after October, 2016
Is it about SHA-1 or there is something else?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> + * Verify that certificate does not use weak signature hash algorithm.
Method description is vague, there should be a detailed explanation on what's considered weak.

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> +AGVerifyResult AGCertificateVerifier::verifyOCSPResponse(const std::string &dnsName, STACK_OF(X509) *certChain,
Public method with no comment

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> +void AGCertificateVerifier::loadDynamicHPKPInfo() {
What does this method do?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> +void AGCertificateVerifier::saveDynamicHPKPInfo() {
Same question as above

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> +AGVerifyResult AGCertificateVerifier::verifyOCSP(const std::string &dnsName, STACK_OF(X509) *certChain) {
What does this method do?
Do you actually make an OCSP request?
Do you check all certificates or just the leaf ones?
What result can be returned?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.cpp
> +    X509 *cert = sk_X509_value(certChain, 0);
If you check the leaf certificate only, what's the point in passing the whole certificate chain? It may be misleading for a library user.

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +        OCSP_FAIL,
What kind of fail? Cannot verify or cannot download?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +        INVALID_CONFIGURATION,
What does that mean?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +    enum AGVerifyResultType {
Every result type should have a detailed description

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +     * Create certificate verifier with given storage path
storage path?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +    void setLocalCAStore(STACK_OF(X509) *certList);
Local or trusted?

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +     * Fetch current CA store currently used in SSL clients
I don't understand what does this method do

2017-07-03 12:20 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +    // Mozilla CA store
Why do we need it?

2017-07-03 12:20 UTC, ameshkov commented on src/AGDataStorage.cpp
> + * Copyright 2017 Performix LLC
Performix LLC -> Adguard Software Ltd.

2017-07-03 12:25 UTC, sfionov commented on src/AGCertificateVerifier.cpp
> + * CRLSets CRX download URL: http://clients2.google.com/service/update2/crx?response=redirect&x=id%3Dhfnkpimlhhgieaddgfemjhofmfblmnib%26v=%26uc
It is just hint to library user, where to get CRL sets CRX file to pass to this library. I will make comment more clear.

2017-07-03 13:09 UTC, hmage commented on README.md
> +#### Initialization
Нету простого примера использования.

Типа (песвдокод):
```c++
#include <AGCertificateVerifier.h>

void f() {
  AGCertificateVerifier verifier(AGSimpleDirectoryStorage());
  STACK_OF(X509) *certChain = /* здесь что-нибудь простое */;
  AGVerifierResult result = verifier.verify("google.com", certChain);
  if (result != OK) abort();
}
```

2017-07-03 13:33 UTC, hmage commented on CMakeLists.txt
> +find_package(OpenSSL REQUIRED)
Думаю надо явно проверять, что openssl 1.1 или выше.

2017-07-03 13:41 UTC, hmage requested changes

2017-07-03 13:41 UTC, hmage commented on test/CMakeLists.txt
> +        COMMAND wget -nv -O "${CRL_SET_BIN}" "http://clients2.google.com/service/update2/crx?response=redirect\\&x=id%3Dhfnkpimlhhgieaddgfemjhofmfblmnib%26v=%26uc"
On my system, wget is not installed by default. `cmake --build .` fails:

```
[ 80%] Generating AGCertificateVerifierTestCrlSet.o
/bin/sh: wget: command not found
make[2]: *** [test/AGCertificateVerifierTestCrlSet.o] Error 127
```

Add a check to CMakeLists.txt: `wget` binary should be in the `PATH`.

2017-07-03 13:41 UTC, hmage commented on test/CMakeLists.txt
> +        COMMAND ld -r -b binary -o "${CRL_SET_OBJ}" "${CRL_SET_BIN}"
On OSX:
```
ld: warning: option -b is obsolete and being ignored
ld: file not found: binary
```

2017-07-03 13:41 UTC, hmage commented on test/CMakeLists.txt
> +        COMMAND objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "${CRL_SET_OBJ}" "${CRL_SET_OBJ}"
on OSX there's no `objcopy`.

2017-07-03 13:44 UTC, sfionov commented on test/CMakeLists.txt
> +        COMMAND objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "${CRL_SET_OBJ}" "${CRL_SET_OBJ}"
Does it compile if you comment this line?

2017-07-03 13:45 UTC, hmage commented on test/CMakeLists.txt
> +        COMMAND objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "${CRL_SET_OBJ}" "${CRL_SET_OBJ}"
Doesn't reach `objcopy`. Fails at `ld`. If I comment out both `ld` and `objcopy` I get this:

```
[ 86%] Linking C static library libtest_verifier_crl_set_blob.a
ar: AGCertificateVerifierTestCrlSet.o: No such file or directory
make[2]: *** [test/libtest_verifier_crl_set_blob.a] Error 1
```

2017-07-03 14:25 UTC, sxgunchenko requested changes

2017-07-03 14:25 UTC, sxgunchenko commented on src/AGCertificateVerifier.cpp
> +        }
checks for static and dynamic pins are similar, i would suggest to place them in a single private method

2017-07-03 14:25 UTC, sxgunchenko commented on src/AGCertificateVerifier.cpp
> +#if 0
is it needed?

2017-07-03 14:25 UTC, sxgunchenko commented on src/AGCertificateVerifier.cpp
> +        break;
here we always quit after the first iteration, is it ok?

2017-07-03 14:25 UTC, sxgunchenko commented on src/AGCertificateVerifier.cpp
> +        BIO_set_nbio(cbio, 1);
no braces here, and in some places below in this method

2017-07-03 14:25 UTC, sxgunchenko commented on src/AGCertificateVerifierStaticData.cpp
> +    }*/
is it needed?

2017-07-03 14:25 UTC, sxgunchenko commented on src/AGCertificateVerifierStaticData.cpp
> +    }
these 2 loops could be implemented in a single method

2017-07-03 14:25 UTC, sxgunchenko commented on src/AGHPKPInfo.cpp
> +    if (name == "includesubdomains") {
let's not do extra checking
`else if (name == "includesubdomains")`

2017-07-03 15:04 UTC, hmage approved these changes

2017-07-03 17:58 UTC, ameshkov requested changes

2017-07-03 17:58 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +     * @param storagePath Path to verifier database (HPKP info)
Why storage path?

2017-07-03 17:58 UTC, ameshkov commented on src/AGCertificateVerifier.h
>       * Verify specified certificate chain
It's not clear what exact checks will be done

2017-07-03 17:58 UTC, ameshkov commented on src/AGCertificateVerifier.h
>      void updateCRLSets(const char *crlSetCrx, size_t crlSetCrxLen);
`crlSetCrx` -- what does this parameter mean?

2017-07-03 17:58 UTC, ameshkov commented on src/AGCertificateVerifier.h
> +    AGVerifyResult verifyCrlSetsStatus(STACK_OF(X509) *certChain);
What are the pre-requisites for this method to work properly?
What if I didn't call updateCrlSets prior to this call?

2017-07-03 17:58 UTC, ameshkov commented on src/AGCertificateVerifier.h
>      AGVerifyResult verifyPins(const std::string &dnsName, STACK_OF(X509) *certChain);
What are these pins? Are they updated? If not, please explain how pins are supposed to be updated

2017-07-03 17:58 UTC, ameshkov commented on src/AGCertificateVerifier.h
>      AGVerifyResult verifyUntrustedAuthority(STACK_OF(X509) *certChain);
Still unclear what certificates are untrusted, it should be explicitly described

2017-07-04 11:10 UTC, sfionov commented on src/AGCertificateVerifierStaticData.cpp
> +    }
Fixed.

2017-07-04 11:11 UTC, sfionov commented on src/AGCertificateVerifier.h
>      AGVerifyResult verifyUntrustedAuthority(STACK_OF(X509) *certChain);
Added method description into implementation file.

2017-07-04 11:13 UTC, sfionov commented on src/AGCertificateVerifier.cpp
> +        break;
Yes, there is zero or one url.

2017-07-04 11:19 UTC, sfionov reviewed
Updated pull request. All private methods are commented in cpp file.

2017-07-04 11:19 UTC, sfionov commented on src/AGCertificateVerifier.h
> +    AGVerifyResult verifyCrlSetsStatus(STACK_OF(X509) *certChain);
Added description of private method into implementation cpp file.

2017-07-04 11:45 UTC, ameshkov approved these changes

2017-07-04 13:07 UTC, sxgunchenko approved these changes

2017-07-04 13:19 UTC, merged